version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=node-test
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root -d node-test']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
  node-app:
    build: .
    image: node-test
    restart: always
    environment:
      - PORT=3000
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=node-test
    links:
      - postgres:postgres
    depends_on: 
      postgres:
        condition: service_healthy
    ports:
      - 3000:3000